---
- hosts: ubuntu2204
  become: yes

  vars:
    osquery_version: 5.11.0-1

  tasks:
  - name: Instalacion de Osquery
    ansible.builtin.apt:
      deb: "https://pkg.osquery.io/deb/osquery_{{ osquery_version }}.linux_amd64.deb"
      state: present
      
  - name: Copiar archivo de configuracion 
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../../files/osquery/osquery.conf"
      dest: "/etc/osquery/osquery.conf"
      backup: no
      owner: root
      group: root
      mode: 0644
      
  - name: Iniciar servicio Osquery
    ansible.builtin.systemd:
      name: osqueryd
      state: started
      enabled: yes
