---
- name: Install Podman, Podman Compose on Ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Podman
      apt:
        name: podman
        state: present

    - name: Install Podman Compose
      apt:
        name: podman-compose
        state: present