all:
  hosts:
    127.0.0.1:
  children:
    linux:
      hosts:
        127.0.0.1:
        k01.rodolfoarce.local:
        k02.rodolfoarce.local:
        k03.rodolfoarce.local:
        redmine01.rodolfoarce.local:
        test01.rodolfoarce.local:
        test02.rodolfoarce.local:
        wazuh01.rodolfoarce.local:
        web01.rodolfoarce.local:
      children:
        ubuntu:
          hosts:
            127.0.0.1:
            k01.rodolfoarce.local:
            k02.rodolfoarce.local:
            k03.rodolfoarce.local:
            redmine01.rodolfoarce.local:
            test01.rodolfoarce.local:
            test02.rodolfoarce.local:
            wazuh01.rodolfoarce.local:
            web01.rodolfoarce.local:
          children:
            ubuntu2204:
              hosts:
                127.0.0.1:
                redmine01.rodolfoarce.local:
                test01.rodolfoarce.local:
                wazuh01.rodolfoarce.local:
                web01.rodolfoarce.local:
              children:
                ubuntu2204-k3s:
                  hosts:
                    127.0.0.1:
                    k01.rodolfoarce.local:
                    k02.rodolfoarce.local:
                    k03.rodolfoarce.local:
            ubuntu2404:
              hosts:
                127.0.0.1:
              children:
                ubuntu2404-docker:
                  hosts:
                    test02.rodolfoarce.local:
          vars:
            ansible_python_interpreter=/usr/bin/python3
