---
- hosts: ubuntu
  become: yes

  tasks:
    - name: Descargar reglas para Nmap al directorio de reglas de Wazuh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rodolfoarces/wazuh-scripts/main/rules/nmapscan.xml
        dest: /opt/wazuh-scripts/nampscan.py
        mode: '0440'
        owner: wazuh
        group: wazuh